# -----------------------------------------------------------------------------
# kube-apiserver OIDC authenticator, configured on the control-plane node.
#
# kube-apiserver runs as a static pod on the control-plane node, so enabling
# OIDC is a node-level manifest edit + a CA file drop, NOT something GitOps or
# the kind_config can express. Two pieces, both keyed to cluster_ca so they
# re-run on a full cluster rebuild (kind delete + apply):
#   1. oidc-ca.crt   - the platform-tls CA (same self-signed cert generated by
#      platform-tls.tf), copied to /etc/kubernetes/pki/oidc-ca.crt so the
#      apiserver trusts Keycloak's TLS when it fetches OIDC discovery/JWKS.
#   2. the --oidc-* flags on the kube-apiserver static-pod manifest (via
#      apiserver-oidc/configure-apiserver-oidc.sh, run inside the node).
#
# The issuer must match the `iss` claim Keycloak bakes into its tokens
# byte-for-byte, so it reuses var.argocd_oidc_issuer_url (the platform's single
# Keycloak issuer) rather than a separate, drift-prone copy. The client id is
# teams-cli: only tokens minted for that client authenticate here (teams-ui
# browser tokens have a different aud and are correctly rejected — `teams-cli
# login` is what feeds kubectl).
#
# Configuring OIDC does not require Keycloak to be reachable at apiserver start:
# with the legacy --oidc-* flags discovery/JWKS are fetched lazily, at token
# validation time — so this is safe to apply before Argo CD deploys Keycloak.
# The node /etc/hosts entry that lets the apiserver reach Keycloak once it IS up
# is handled by node-hosts.tf; we depend on it so the two land together.
#
# Replaces the manual "step 2" (apiserver OIDC flags + oidc-ca.crt) in
# platform-infra/bootstrap/README.md.
# -----------------------------------------------------------------------------

resource "null_resource" "apiserver_oidc" {
  count = var.apiserver_oidc_enabled ? 1 : 0

  triggers = {
    # Rebuild reissues the cluster CA, forcing a re-run on a fresh cluster.
    cluster_ca = sha256(kind_cluster.this.cluster_ca_certificate)
    # Re-run if the platform-tls cert rotates (refreshes oidc-ca.crt).
    cert_hash = local_file.platform_tls_crt.content_md5
    # Re-run if the configure script changes.
    script_hash = filemd5("${path.module}/apiserver-oidc/configure-apiserver-oidc.sh")
    # Re-run if any OIDC parameter changes.
    params = join(",", [
      var.argocd_oidc_issuer_url,
      var.apiserver_oidc_client_id,
      var.apiserver_oidc_username_claim,
      var.apiserver_oidc_groups_claim,
    ])
  }

  provisioner "local-exec" {
    interpreter = ["/bin/sh", "-c"]
    # Point the docker CLI at the same daemon the docker provider uses (colima).
    environment = {
      DOCKER_HOST = var.docker_host
    }
    command = <<-EOT
      set -e
      node="${var.cluster_name}-control-plane"

      # 1. Drop the platform-tls CA where the apiserver expects the OIDC CA.
      docker cp "${path.module}/${var.platform_tls_output_dir}/platform-tls.crt" \
        "$node:/etc/kubernetes/pki/oidc-ca.crt"

      # 2. Copy + run the manifest-edit script inside the node.
      docker cp "${path.module}/apiserver-oidc/configure-apiserver-oidc.sh" \
        "$node:/usr/local/bin/configure-apiserver-oidc.sh"
      docker exec \
        -e ISSUER_URL="${var.argocd_oidc_issuer_url}" \
        -e CLIENT_ID="${var.apiserver_oidc_client_id}" \
        -e USERNAME_CLAIM="${var.apiserver_oidc_username_claim}" \
        -e GROUPS_CLAIM="${var.apiserver_oidc_groups_claim}" \
        -e CA_PATH="/etc/kubernetes/pki/oidc-ca.crt" \
        "$node" sh /usr/local/bin/configure-apiserver-oidc.sh
      echo "apiserver OIDC configured on $node"
    EOT
  }

  # Cluster nodes must exist, the cert file must be written, and the /etc/hosts
  # routing (Keycloak reachability from the node) should be in place first.
  depends_on = [
    kind_cluster.this,
    local_file.platform_tls_crt,
    null_resource.node_hosts_fix,
  ]
}
