# SSO: native OIDC against Keycloak's "teams" realm (not the bundled Dex) -
# there's exactly one IdP in this cluster, so Dex's extra hop buys nothing.
# The counterpart "argocd" Keycloak client lives in a completely different
# deploy mechanism (platform-infra's teams-realm.json, applied via Argo CD's
# own Helm release of Keycloak) - these locals are the seam between the two;
# keep clientID/clientSecret/issuer in sync with that file by hand, nothing
# enforces it automatically.
#
# Argo CD's OIDC RBAC only matches the token's `groups` claim (not
# realm_access.roles), so admin access is granted to a *group*
# (var.argocd_admin_group) rather than reusing the realm's existing "admin"
# role directly - see variables.tf.
#
# Reachability: platform-auth.127.0.0.1.sslip.io resolves to 127.0.0.1 (the
# whole point of sslip.io), which from *inside* argocd-server means its own
# loopback, not the ingress - and Keycloak's issuer has :8443 hardcoded
# (its --hostname flag, platform-infra's keycloak Application), which the
# ingress-nginx Service doesn't listen on internally at all (only 80/443;
# :8443 is a kind Docker port mapping, host-only). Both fixed out-of-band,
# not by Terraform: a CoreDNS rewrite (platform-auth.127.0.0.1.sslip.io ->
# platform-auth-ingress-8443.ingress-nginx.svc.cluster.local) and that
# small additional Service (same pod selector as ingress-nginx-controller's
# own Service, just also exposing :8443) - see
# platform-infra/apps/security/keycloak/application.yaml's extraManifests.
#
# RBAC ownership: once OIDC is on, argocd-rbac-cm is deliberately NOT owned
# by this Helm release (configs.rbac.create=false below) - it's owned by
# Terraform (kubernetes_config_map.argocd_rbac, static baseline only) with
# teams-operator as the sole runtime writer of everything else (per-project
# viewer/maintainer policy blocks). Argo CD hot-reloads this ConfigMap via
# an informer watch - no restart needed, unlike timeout.reconciliation
# above - so that split is safe. See kubernetes_config_map.argocd_rbac's own
# comment for why this doesn't race with the chart on the cutover apply.

# platform-tls is generated by Terraform (see platform-tls.tf), NOT read from the
# keycloak namespace secret. That read was a chicken-and-egg: Argo CD creates
# Keycloak + its platform-tls secret only AFTER this apply, so reading it here
# failed the first OIDC-enabled apply (and, with the kubernetes provider host
# unresolved at read time, surfaced as "dial tcp [::1]:80: connection refused").
# As a Terraform resource the cert is available on the first apply instead.

locals {
  argocd_cm_config = merge(
    {
      # How often the application-controller re-checks git and reconciles each
      # Application (argocd-cm `timeout.reconciliation`). Default is 180s, which
      # meant a merged image-bump PR took up to 3 min to deploy. 30s makes merged
      # Renovate bumps roll out in seconds. (A git webhook would be instant, but
      # GitHub can't reach this local kind cluster, so a short poll is the lever.)
      # NOTE: the controller reads this at startup — after `terraform apply`,
      # restart it: kubectl -n argocd rollout restart statefulset argocd-application-controller
      "timeout.reconciliation" = "30s"
      # The chart's own default ("https://argocd.example.com") was never
      # overridden - Argo CD builds its OAuth redirect_uri as "<url>/auth/
      # callback", so it was sending that placeholder straight to Keycloak
      # ("Invalid redirect URL", since it obviously doesn't match what's
      # registered on the "argocd" client). Must exactly match
      # var.argocd_ingress_host's scheme+host+port, which is also what the
      # Keycloak client's redirectUris/webOrigins are registered against
      # (platform-infra/apps/security/keycloak/application.yaml).
      "url" = "http://${var.argocd_ingress_host}:${var.ingress_http_host_port}"
    },
    var.argocd_oidc_enabled ? {
      "oidc.config" = yamlencode({
        name     = "Keycloak"
        issuer   = var.argocd_oidc_issuer_url
        clientID = "argocd"
        # Argo CD's own $<secret-name>:<key> interpolation - resolved from
        # argocd-secret at read time, never written into this ConfigMap or
        # Terraform state as plaintext. The key must match what's set in
        # configs.secret.extra below.
        clientSecret = "$argocd-secret:oidc.keycloak.clientSecret"
        # "groups" is deliberately NOT requested here - it isn't a real
        # scope (no Keycloak client scope named "groups" exists in this
        # realm), and requesting it fails with invalid_scope. The groups
        # claim still lands in the token regardless, via the protocol
        # mapper attached directly to the "argocd" client (same pattern as
        # teams-ui/teams-cli) - RBAC's own configs.rbac.scopes (defaults to
        # "[groups]") reads that claim, unrelated to what's requested here.
        requestedScopes = ["openid", "profile", "email"]
        # platform-tls is self-signed; without this argocd-server rejects
        # the connection ("x509: certificate signed by unknown authority").
        # Sourced from the Terraform-generated cert (platform-tls.tf), so it is
        # available on the first apply with OIDC enabled and stays in lockstep
        # with the cert create-secrets.sh distributes to the other namespaces.
        rootCA = tls_self_signed_cert.platform_tls.cert_pem
        # Without this, Argo CD's own logout only clears its local session -
        # the Keycloak SSO session (KEYCLOAK_SESSION cookie) stays alive, so
        # logging back in silently re-authenticates via SSO with no password
        # prompt. logoutURL makes Argo CD redirect to Keycloak's RP-initiated
        # logout (end_session) endpoint on the way out, ending that session
        # too. {{token}}/{{logoutRedirectURL}} are Argo CD's own template
        # placeholders (id_token from the session, and its own base `url`
        # above, respectively) - not Terraform interpolation, hence the
        # single-quote-free literal braces surviving yamlencode as-is.
        # post_logout_redirect_uri must be pre-registered on the "argocd"
        # Keycloak client's post.logout.redirect.uris attribute (platform-
        # infra/apps/security/keycloak/application.yaml) or Keycloak rejects
        # the redirect after logout.
        logoutURL = "${var.argocd_oidc_issuer_url}/protocol/openid-connect/logout?id_token_hint={{token}}&post_logout_redirect_uri={{logoutRedirectURL}}"
      })
    } : {}
  )

  argocd_secret_extra = var.argocd_oidc_enabled ? {
    "oidc.keycloak.clientSecret" = var.argocd_oidc_client_secret
  } : {}

  argocd_rbac_config = var.argocd_oidc_enabled ? {
    # Hand ownership of argocd-rbac-cm's *content* to Terraform + teams-operator
    # (see kubernetes_config_map.argocd_rbac below) instead of this chart -
    # "it is expected the configmap will be created by something else" per the
    # chart's own docs. Previously this block set policy.csv/policy.default
    # directly here, which meant *every* logged-in user got Argo CD's built-in
    # role:readonly by default (read access to */* - every project, cluster-
    # wide) - that was the root cause of a non-admin user seeing platform-
    # internal apps like cert-manager. Fixed by removing policy.default
    # entirely (no global fallback role) as part of this ownership handoff.
    "create" = false
  } : {}
}

# Argo CD, installed via its official Helm chart.
# Chart docs: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
resource "helm_release" "argocd" {
  count = var.argocd_enabled ? 1 : 0

  name             = "argocd"
  namespace        = var.argocd_namespace
  create_namespace = true

  repository = "https://argoproj.github.io/argo-helm"
  chart      = "argo-cd"
  version    = var.argocd_chart_version != "" ? var.argocd_chart_version : null

  # Run argocd-server in insecure (plain-HTTP) mode. Behind an HTTP ingress this
  # is required: in TLS mode the server marks the auth cookie `Secure`, which
  # browsers drop over http:// — so login silently fails. ingress-nginx is the
  # edge here; TLS can be terminated at the ingress later if desired.
  values = [yamlencode({
    configs = {
      params = {
        "server.insecure" = true
      }
      cm     = local.argocd_cm_config
      secret = { extra = local.argocd_secret_extra }
      rbac   = local.argocd_rbac_config
    }
    # Dex is unused once native OIDC (above) is configured - one less
    # component to run/patch/debug. Left enabled if OIDC is off, so a
    # from-scratch cluster still gets a working (local-admin-only) Argo CD.
    dex = {
      enabled = !var.argocd_oidc_enabled
    }
  })]

  # Block until the release's resources report ready so downstream steps can
  # rely on Argo CD being usable.
  wait    = true
  timeout = 600

  depends_on = [kind_cluster.this]
}

# Static RBAC baseline for argocd-rbac-cm, owned by Terraform going forward -
# NOT the argo-cd chart (configs.rbac.create=false above hands this off).
# teams-operator is the runtime owner of everything else: per-project
# viewer/maintainer policy blocks, added/updated/removed via a direct
# read-modify-write of this same ConfigMap's `policy.csv`, delimited per
# project (`# BEGIN project <name>` / `# END project <name>`) so it never
# touches this baseline. `ignore_changes = [data]` is what makes that safe -
# without it, the next `terraform apply` that touches this release (e.g. a
# chart version bump forcing a helm upgrade) would re-render and overwrite
# every project's policy back to just this baseline, silently wiping
# self-service state that lives only in the live cluster.
#
# Ordering on the cutover apply (the one that flips argocd_oidc_enabled from
# false to true, or adds this resource against an already-oidc-enabled
# release): helm_release.argocd's upgrade deletes the ConfigMap it
# previously owned first (no longer rendered, once configs.rbac.create is
# false - standard Helm3 prune-on-upgrade behavior), and depends_on below
# guarantees this resource's Create only runs after that upgrade completes -
# so it never conflicts with the chart's own copy.
#
# NOTE: same two-pass bootstrap caveat as the rootCA comment above - on a
# from-scratch cluster's very first apply, set argocd_oidc_enabled=false so
# the chart creates+owns an initial argocd-rbac-cm the normal way (letting
# argocd-server start successfully); only on a second apply, with oidc
# enabled, does ownership hand off to this resource. Applying with oidc
# enabled from a truly empty cluster on the *first* apply would have
# argocd-server fail to start (no ConfigMap yet for its volume mount, and
# this resource - depending on helm_release.argocd - runs too late to help).
resource "kubernetes_config_map" "argocd_rbac" {
  count = var.argocd_enabled && var.argocd_oidc_enabled ? 1 : 0

  metadata {
    name      = "argocd-rbac-cm"
    namespace = var.argocd_namespace
    labels = {
      "app.kubernetes.io/part-of"    = "argocd"
      "app.kubernetes.io/managed-by" = "terraform"
    }
  }

  data = {
    # Only var.argocd_admin_group members get role:admin. Deliberately no
    # policy.default (no global fallback role) - see local.argocd_rbac_config's
    # comment for why. Per-project viewer/maintainer policy lines are added
    # below this baseline, at runtime, by teams-operator.
    "policy.csv" = "g, ${var.argocd_admin_group}, role:admin\n"
    "scopes"     = "[groups]"
  }

  lifecycle {
    ignore_changes = [data]
  }

  depends_on = [helm_release.argocd]
}

# Ingress exposing the Argo CD server UI through ingress-nginx at
# http://<argocd_ingress_host>:<ingress_http_host_port> (default
# http://argocd.127.0.0.1.sslip.io:8080).
#
# argocd-server runs in insecure (plain-HTTP) mode (see the helm_release above),
# so nginx just proxies HTTP to the server's http port. Serving over HTTP also
# keeps the auth cookie non-Secure, so it survives the http:// browser session.
#
# Note: the ingress-nginx controller itself is installed out-of-band (as an
# Argo CD Application in platform-infra), so this Ingress object may exist before
# a controller is present; it simply isn't routable until one is.
resource "kubernetes_ingress_v1" "argocd" {
  count = var.argocd_enabled && var.argocd_ingress_enabled ? 1 : 0

  metadata {
    name      = "argocd-server"
    namespace = var.argocd_namespace
  }

  spec {
    ingress_class_name = "nginx"

    rule {
      host = var.argocd_ingress_host
      http {
        path {
          path      = "/"
          path_type = "Prefix"
          backend {
            service {
              name = "argocd-server"
              port {
                name = "http"
              }
            }
          }
        }
      }
    }
  }

  # The argocd-server Service is created by the Helm release above.
  depends_on = [helm_release.argocd]
}
