# -----------------------------------------------------------------------------
# Durable containerd trust of the platform-tls CA on every kind node.
#
# Harbor serves its registry over the self-signed *.127.0.0.1.sslip.io cert
# (platform-tls). containerd on each node pulls tenant/platform images from
# Harbor, so it must trust that CA — otherwise every pull fails with
# "x509: certificate signed by unknown authority" / ErrImagePull.
#
# The cert is already generated by Terraform (platform-tls.tf) and written to
# bootstrap/platform-tls.crt, so we just install it into each node's system
# trust store and reload containerd. Keyed to cluster_ca (like node-hosts.tf),
# this re-runs on a full cluster rebuild (kind delete + apply). Unlike
# /etc/hosts, /usr/local/share/ca-certificates is NOT regenerated on a node
# restart, so a one-shot provisioner is enough — no boot-time systemd unit.
#
# This is node-level plumbing outside Kubernetes' reach, so it cannot be
# GitOps-managed. Replaces the manual "step 2" containerd CA trust in
# platform-infra/bootstrap/README.md.
# -----------------------------------------------------------------------------

resource "null_resource" "node_containerd_ca" {
  # local.kind_nodes is defined in node-hosts.tf.
  for_each = toset(local.kind_nodes)

  triggers = {
    # Rebuild reissues the cluster CA, forcing a re-run on a fresh cluster.
    cluster_ca = sha256(kind_cluster.this.cluster_ca_certificate)
    # Re-run if the platform-tls cert itself rotates.
    cert_hash = local_file.platform_tls_crt.content_md5
    node      = each.value
  }

  provisioner "local-exec" {
    interpreter = ["/bin/sh", "-c"]
    # Point the docker CLI at the same daemon the docker provider uses (colima).
    environment = {
      DOCKER_HOST = var.docker_host
    }
    command = <<-EOT
      set -e
      node="${each.value}"
      docker cp "${path.module}/${var.platform_tls_output_dir}/platform-tls.crt" \
        "$node:/usr/local/share/ca-certificates/platform-tls.crt"
      docker exec "$node" update-ca-certificates
      docker exec "$node" systemctl restart containerd
      echo "platform-tls CA trusted by containerd on $node"
    EOT
  }

  # Cluster (nodes) must exist and the cert file must be written first.
  depends_on = [kind_cluster.this, local_file.platform_tls_crt]
}
